mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
     - "27017:27017"

yremote:
    image: dreg.tikalknowledge.com:5000/yremote/yremote:${YR_VERSION}
    container_name: yremote
    links:
     - mongodb:mongodb
    ports:
     - "3000:3000"

ynginx:
    image: dreg.tikalknowledge.com:5000/yremote/ynginx:${YR_VERSION}
    container_name: ynginx
    ports:
     - "80:80"
     - "443:443"

