version: "3"
services:

  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
       - "27017:27017"

  yremote:
      image: yremote:$YR_VERSION
      container_name: yremote
      depends_on:
       - mongodb
      ports:
       - "3000:3000"

  ynginx:
      image: ynginx:$YR_VERSION
      container_name: ynginx
      depends_on:
       - yremote
      ports:
       - "80:80"
       - "443:443"
       - "81:81"
