mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
     - "27017:27017"

yremote:
    image: localhost:5000/yremote/yremote:$YR_VERSION
    container_name: yremote
    links:
     - mongodb:mongodb
    ports:
     - "3000:3000"

ynginx:
    image: localhost:5000/yremote/ynginx:$YR_VERSION
    container_name: ynginx
    links:
     - yremote:yremote
    ports:
     - "80:80"
     - "443:443"
     - "81:81"
